package br.com.tiagohs.core.network.tmdb

const val QUERY_API_KEY = "api_key"
const val QUERY_APPEND_TO_RESPONSE = "append_to_response"

const val QUERY_LANGUAGE = "language"
const val QUERY_COUNTRY = "country"
const val QUERY_PAGE = "page"
const val QUERY_REGION = "region"
const val QUERY_QUERY = "query"

const val QUERY_SORT_BY = "sort_by"
const val QUERY_CERTIFICATION_COUNTRY = "certification_country"
const val QUERY_CERTIFICATION = "certification"
const val QUERY_CERTIFICATION_LTE = "certification.lte"
const val QUERY_CERTIFICATION_GTE = "certification.gte"
const val QUERY_INCLUDE_IMAGE_LANGUAGE = "include_image_language"
const val QUERY_INCLUDE_VIDEO_LANGUAGE = "include_video_language"
const val QUERY_INCLUDE_ADULT = "include_adult"
const val QUERY_INCLUDE_VIDEO = "include_video"
const val QUERY_PRIMARY_RELEASE_YEAR = "primary_release_year"
const val QUERY_PRIMARY_RELEASE_GTE = "primary_release_date.gte"
const val QUERY_PRIMARY_RELEASE_LTE = "primary_release_date.lte"
const val QUERY_RELEASE_DATE_GTE = "release_date.gte"
const val QUERY_RELEASE_DATE_LTE = "release_date.lte"
const val QUERY_YEAR = "year"
const val QUERY_VOTE_COUNT_GTE = "vote_count.gte"
const val QUERY_VOTE_COUNT_LTE = "vote_count.lte"
const val QUERY_VOTE_AVERAGE_GTE = "vote_average.gte"
const val QUERY_VOTE_AVERAGE_LTE = "vote_average.lte"
const val QUERY_RELEASE_TYPE = "with_release_type"
const val QUERY_WITH_CAST = "with_cast"
const val QUERY_WITH_CREW = "with_crew"
const val QUERY_WITH_PEOPLE = "with_people"
const val QUERY_WITH_COMPANIES = "with_companies"
const val QUERY_WITH_GENRES = "with_genres"
const val QUERY_WITHOUT_GENRES = "without_genres"
const val QUERY_WITH_KEYWORDS = "with_keywords"
const val QUERY_WITHOUT_KEYWORDS = "without_keywords"
const val QUERY_WITH_RUNTIME_GTE = "with_runtime.gte"
const val QUERY_WITH_RUNTIME_LTE = "with_runtime.lte"
const val QUERY_WITH_ORIGINAL_LANGUAGE = "with_original_language"
const val QUERY_WITH_WATCH_PROVIDERS = "with_watch_providers"
const val QUERY_WATCH_REGION = "watch_region"
const val QUERY_WITH_WATCH_MONETIZATION_TYPES = "with_watch_monetization_types"
const val QUERY_WITHOUT_COMPANIES = "without_companies"